# Используем конкретную версию Python для стабильности
FROM python:3.12-slim

WORKDIR /app

# Создаем пользователя для повышения безопасности
# синтаксис Debian, тк python-slim основан на нем
RUN groupadd -r appgroup && useradd -r -g appgroup -u 1001 appuser

# Устанавливаем зависимости
# Копируем только requirements.txt сначала для кэширования слоев
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Копируем код приложения
COPY . .

# Создаем папку для логов и назначаем права
RUN mkdir -p /app/logs && chown -R appuser:appgroup /app

# Переключаемся на пользователя
USER appuser

EXPOSE 7000

# Запускаем приложение от имени пользователя
CMD ["python", "main.py"]
