apiVersion: v1
kind: ConfigMap
metadata:
  name: habr-app-config
  labels:
    app: habr-adapter
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  HABR_ADAPTER_PORT: "7000"
  DEV_MODE: "False"